### ISSUE TITLE
Table name normalization required

### ISSUE THREAD

**Issue by sokcuri** [i-van/mysql-emulator#1]
It seems that the behavior is different depending on the syntax of SQL.

```
`INFORMATION_SCHEMA`.`SCHEMATA`
`INFORMATION_SCHEMA.SCHEMATA`
```

This table are the same table, but mysql-emulator treats them differently

**Comment by i-van** [comment]
First issue 🎉!

MySQL thinks that \`INFORMATION_SCHEMA.SCHEMATA\` is table name and will return error like
```
Query 1 ERROR: Table 'mysql_emulator.INFORMATION_SCHEMA.SCHEMATA' doesn't exist
```
as mysql-emulator does when you select something from that table.

Could you add a query that failed to comments?

**Comment by sokcuri** [comment]
I was mistaken. If it consists of backtick, it seems to be regarded as one table name. It's working great!
